### ISSUE TITLE
haskellTopLevelDecl regex slow on larger files

### ISSUE THREAD

**Issue by attheicearcade** [raichoo/haskell-vim#15]
I found noticeable delay when scrolling towards the end of files > 200 lines long. 
Removing the line defining haskellTopLevelDecl solves the issue.

**Comment by raichoo** [comment]
I don't really experience this issue on my machine but I could make the toplevel highlighting optional so one can turn it off when stuff like that happens. Maybe it's possible to tweak more performance out of the highlighter but I'm currently unaware of how to do that.

Kind regards,
raichoo

**Comment by raichoo** [comment]
I simplified the regex to match the top level identifiers. Maybe this speeds it up on your machine. Please give it a try.

Kind regards,
raichoo

**Comment by attheicearcade** [comment]
Works perfectly. Thanks for this plugin, it's fantastic.

**Comment by raichoo** [comment]
Thank you :)
