### ISSUE TITLE
Don't indent after let in do-block

### ISSUE THREAD

**Issue by orbisvicis** [raichoo/haskell-vim#16]
```
.......................................................... $ do
    a <- ...
    b <- ...
    let c = ...
        |<--cursor here
```

Also congrats on being the only haskell syntax highlighter that doesn't choke (slow to a crawl) on match paren. I think this is because () and [] aren't being scanned for tuple/list constructor highlighting.

**Comment by raichoo** [comment]
Checking if you are in a do block would mean that you'd need to check every line above that the current line and also needs to understand nesting of do-blocks. This is simply to much for Vim since the mechanisms it provides are pretty primitive.

**Comment by orbisvicis** [comment]
I'm not sure understanding nested do-blocks is required. However shouldn't vim's syntax-sync options help in backsearching, such that minlines=100  seems reasonable?

**Comment by raichoo** [comment]
Let indentation is already pretty fragile. I really don't want to make his any more complicated. Indentation in Vim will never be perfect with the current tools. I really want to get around with as little backsearching as possible since it's prone to break.

**Comment by raichoo** [comment]
On the other hand I also write:

        let a = 1
            b = 2

etc pretty often. If you really want to have this behavior consider writing a patch and make this behavior configurable with a flag.

Kind regards,
raichoo

**Comment by raichoo** [comment]
Let me give you some code where this would cause trouble:

        fundo = do -- 2) oh i found one! therefore don't indent
          return 1

        fun x = let x = 1
                    y -- 1) ok lets indent this look up to find a 'do'

        -- 3) ok lets also stop search once we have found something
        -- that starts at column 0

        -- this won't work in a where block

        test = …
          where
            fundo = do
              return 1

            fun x = let x = 1
                        y

**Comment by orbisvicis** [comment]
> On the other hand I also write: ... etc in do-blocks pretty often.

No, that by itself is a good reason to keep the current behaviour. And the later example code is also very troubling.
