### ISSUE TITLE
Usage of ftdetect

### ISSUE THREAD

**Issue by ruedigerha** [raichoo/haskell-vim#19]
Regarding your recent commit e8a3cb0f0e68adef6ac34387e42db8eb00ee1282, are you sure that the file in `ftdetect` is supposed to set local options? I thought it was only for determining the filetype (and I think the default detection is fine) and that options should go into `ftplugin`.

The point is, I occasionally start a new unnamed buffer and just do a `set ft=haskell`. The `setlocal` calls from `ftdetect` then won't become active until I've written and reloaded that file with a `*.hs` filename. I'm worried a bit about options set differently depending on how I started working on a Haskell file.

**Comment by raichoo** [comment]
This is currently the only place that seems to work to actually set these settings without them being overwritten from another place. I suppose I could move the `comments` into another file. Not setting these options results in some functions to behave in a way I don't want them to.

If you have a better solution: patches welcome.

Kind regards,
raichoo

**Comment by ruedigerha** [comment]
You're correct, I checked and the format options are overridden when placed in `ftplugin`. I have made a pull request in which I moved the `setlocal` calls into `after/ftplugin` where they shouldn't be overridden by defaults. You can try if this works for you, too.

**Comment by raichoo** [comment]
I moving them into `after/ftplugin` also covers your use case feel free to send me a pull request. I will merge it :)

**Comment by ruedigerha** [comment]
I have already opened pull request #20.
