### ISSUE TITLE
Character literals are not highlighted correctly

### ISSUE THREAD

**Issue by wilywampa** [raichoo/haskell-vim#21]
The following code
```haskell
main = print $ '"' : foo
  where foo = "bar"
```
is highlighted like this:
![screen shot 2015-03-16 at 6 26 19 pm](https://cloud.githubusercontent.com/assets/4472522/6679757/0f13b3d6-cc0a-11e4-94fc-b7789f3e0e13.png)
with the string not being terminated at the second quote. When I change what's in the single quotes to anything else, the string problem goes away, but I can't seem to get anything to be highlighted as "haskellChar".

**Comment by wilywampa** [comment]
I did a git bisect and found that 8a79122ec34d24b96a47b7c8af2db5325020d804 caused the issue. Reverting those changes fixes it but at the cost of operators containing single quotes.

**Comment by raichoo** [comment]
Thanks. I fixed it and hopefully others things did not break.
