### ISSUE TITLE
.hsc is a Haskell file format

### ISSUE THREAD

**Issue by osa1** [raichoo/haskell-vim#22]
First of all, thanks for this awesome work. I just switched from vim2hs and this is way better.

I'm working on `.hsc` files a lot, vim2hs was considering those files as Haskell files and enabling ft automatically. Adding same thing to haskell-vim would be nice.

(I currently have something like `au! BufRead,BufNewFile *.hsc set filetype=haskell` in my .vimrc)

**Comment by raichoo** [comment]
Added an ftdetect file that should take care of that.
