### ISSUE TITLE
Haskell syntax colours break with primes

### ISSUE THREAD

**Issue by alxgnon** [raichoo/haskell-vim#24]
```hs
-- CASE 1
foo = bar'baz
-- Line not highlighted as comment
-- Line highlighted as comment
```

```hs
-- CASE 2
foo = bar'f'oo
-- 'f' is highlighted as a character literal
```

These two examples break the syntax colouring.

I've seen case 1 in actual code. I've never seen case 2, I just discovered it while investigating the cause of case 1.

I tried fixing this myself, changing the parts of the syntax file that assume primes can only be found at the end of a name. This did not fix case 1, and it obviously did not affect case 2.

**Comment by alxgnon** [comment]
Here are two (symmetrical) cases I also found:

```hs
--- CASE 3
foo = foo'Bar
-- Bar is highlighted as a type
-- (looks like this also breaks github's syntax colours)
```
```hs
--- CASE 4
foo :: Int -> Bar'foo
-- Only the Bar' part is highlighted
```

In https://github.com/alxgnon/haskell-vim/commit/a463c1f1e19e6ca5fbf641099e851a130f3f6401 I try the obvious fix. Unfortunately, this only fixes case 4.

**Comment by raichoo** [comment]
I refactored the quote highlighting. It's actually pretty hard to catch these edge cases but I hope this covers most of it. 890395d

**Comment by alxgnon** [comment]
Seems to be working great. Thank you for fixing this!

**Comment by raichoo** [comment]
You're welcome.
