### ISSUE TITLE
Highlighting "TODO", "FIXME", etc.

### ISSUE THREAD

**Issue by osa1** [raichoo/haskell-vim#25]
It seems like most language syntax files do this, including `vim2hs`. I'm no vimscript pro, but I think `haskell-vim` doesn't highlight `Todo` syntax group, so even if I add this to my .vimrc:

```vimscript
syn match   myTodo   contained   "\<\(TODO\|FIXME\):"
hi def link myTodo Todo
```

It still doesn't highlight. Adding this would be really awesome.

**Comment by raichoo** [comment]
I included that.
