### ISSUE TITLE
some valid identifiers are not highlighted

### ISSUE THREAD

**Issue by osa1** [raichoo/haskell-vim#26]
Here are some examples:

```
lit_1'Integer
subtract'Integer
exp1 `add'Rational` exp2
```

The part until `'` is not highlighted at all, second part is highlighted as if it's a constructor. If second part doesn't start with upper case letter, then it's not highlighted. (example: ``` `blah'blah` ```)

In addition, third one is not highlighted as an infix operator.

**Comment by raichoo** [comment]
This actually has been fixed a few days ago, You should check this against a recent version of `haskell-vim`

**Comment by osa1** [comment]
You're right. I actually update `haskell-vim` regularly, but as I just realized, I never restart my vim sessions :) Thanks.
