### ISSUE TITLE
Could function names be highlighted?

### ISSUE THREAD

**Issue by Magicloud** [raichoo/haskell-vim#30]
```Haskell
main :: IO () -- currently this line works well.
main = putStrLn "" -- "main" here is rendered as plain text (maybe, I am using solarized color theme).
```
Could "main" in the second line be colorful? Thanks.

**Comment by raichoo** [comment]
Nope, this would need semantic information that Vim does not provide otherwise you'd have to deal with a lot of edge cases that would break in various situations.
