### ISSUE TITLE
`type role` syntax not supported

### ISSUE THREAD

**Issue by osa1** [raichoo/haskell-vim#34]
Example:

```
type role IO representational
{-
comments
-}
```

Comments are highlighted as code. Adding `= ...` to the `type role` line fixes it.

**Comment by raichoo** [comment]
Works for me. Do you have a recent version of `haskell-vim`?

**Comment by osa1** [comment]
You're right! The problem was that I didn't have this:

```viml
let g:haskell_enable_typeroles = 1
```

Sorry for the noise.
