### ISSUE TITLE
Minor highlighting issue with Constr{} style pattern matching

### ISSUE THREAD

**Issue by osa1** [raichoo/haskell-vim#35]
```haskell
isValid NotValid {} = False
data Blah
```

Here `data` is not highlighted properly. But if I change the function to:

```haskell
isValid NotValid{} = False
data Blah
```

(I removed a space) it works!

**Comment by raichoo** [comment]
Should work now.

**Comment by osa1** [comment]
It's even more broken now. Both versions are highlighted wrongly.

**Comment by raichoo** [comment]
Interestingly enough that seemed to work when I tested it, maybe there was something else loaded by Vim. I don't know. Have another try please.

**Comment by osa1** [comment]
Thanks!
