### ISSUE TITLE
String literals in record update not highlighted

### ISSUE THREAD

**Issue by walkie** [raichoo/haskell-vim#39]
String literals in record updates are not highlighted correctly. This used to work but seems to have been broken by 6f0f0f81d34613814dd9bd444687f33f9420db0b.

Example:
~~~
test = x { y = "foo" }
~~~

Expect `"foo"` to be highlighted as a string, but it's not.

**Comment by walkie** [comment]
Actually, it seems to be that everything in the RHS of the `=` is not highlighted correctly.

**Comment by raichoo** [comment]
Looks like this got broken in the process of refactoring some of the block related highlighting. Sadly this stuff can be very unpredictable so thanks for reporting this.

Please check if it works for you now.

**Comment by walkie** [comment]
Yep, this works for me. Thanks!
