### ISSUE TITLE
Alternative function definitions

### ISSUE THREAD

**Issue by alex404** [raichoo/haskell-vim#6]
So I have a very small feature request, namely that when I have very complicated functions, I prefer to write the function type as

<pre><code>function
    :: Classy x
    => x
    -> Foo
    -> Bar
</code></pre>

haskell-vim however does not currently highlight 'function' as a function, but leaves it as plain text.

**Comment by raichoo** [comment]
I've added this. It might become an optional feature in the future since I don't know how this will impact overall performance.

Kind regards,
raichoo

**Comment by alex404** [comment]
Thanks! Works like a charm, for me at least.
